<?php
/**
 * @file
 * Google Analytics Vimeo Video Tracking.
 */

/**
 * Define admin config url.
 */
define("GOOGLEANALYTICS_VIMEO_CONFIG_PAGE_URL", "admin/config/googleanalytics_vimeo");

/**
 * Implements hook_menu().
 */
function googleanalytics_vimeo_menu() {
  $items = array();
  $items[GOOGLEANALYTICS_VIMEO_CONFIG_PAGE_URL] = array(
    'title' => 'Google Analytics Vimeo Video Tracking',
    'description' => 'Configure Google Analytics Vimeo',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer google analytics'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items[GOOGLEANALYTICS_VIMEO_CONFIG_PAGE_URL . '/settings'] = array(
    'title' => 'Google Analytics Vimeo Settings',
    'description' => 'Configure Google Analytics Vimeo Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('googleanalytics_vimeo_settings'),
    'access callback' => TRUE,
    'access arguments' => array('administer google analytics'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'googleanalytics_vimeo.admin.inc',
    'file path' => drupal_get_path('module', 'googleanalytics_vimeo'),
  );
  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function googleanalytics_vimeo_libraries_info() {
  $libraries['vimeo.ga.js'] = array(
    'name' => 'Google Analytics Vimeo Video Tracking',
    'vendor url' => 'https://github.com/sanderheilbron/vimeo.ga.js',
    'download url' => 'https://github.com/sanderheilbron/vimeo.ga.js/archive/master.zip',
    'version arguments' => array(
      'file' => 'vimeo.ga.min.js',
      'pattern' => '/vimeo.ga.js \| v(\d+\.+\d+)/',
      'lines' => 2,
    ),
    'files' => array(
      'js' => array(
        'vimeo.ga.min.js',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_page_alter().
 */
function googleanalytics_vimeo_page_alter(&$page) {
  module_load_include('inc', 'googleanalytics_vimeo', 'googleanalytics_vimeo');
  $library = libraries_detect('vimeo.ga.js');
  $googleanalytics_vimeo_visibility_pages = googleanalytics_vimeo_visibility_pages();
  if (!empty($library['installed']) && !empty($googleanalytics_vimeo_visibility_pages)) {
    libraries_load('vimeo.ga.js');
    drupal_add_js(drupal_get_path('module', 'googleanalytics_vimeo') . '/googleanalytics_vimeo.js', array('scope' => 'footer'));
  }
  googleanalytics_vimeo_admin_config_js();
}

/**
 * Implements hook_js_alter().
 */
function googleanalytics_vimeo_js_alter(&$javascript) {
  $library_path = libraries_get_path('vimeo.ga.js');
  if (isset($javascript[$library_path . '/vimeo.ga.min.js'])) {
    $javascript[$library_path . '/vimeo.ga.min.js']['scope'] = 'footer';
  }
}
