<?php
/**
 * @file
 * Google Analytics Vimeo Video Tracking.
 */

/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
function google_analytics_vimeo_page_attachments(array &$page) {
  module_load_include('inc', 'google_analytics_vimeo', 'google_analytics_vimeo');
  $config = \Drupal::config('google_analytics_vimeo.admin_settings');
  $google_analytics_vimeo_visibility_pages = google_analytics_vimeo_visibility_pages();
  $tracking_options = $config->get('visibility.tracking_options');
  $tracking_options = !empty($tracking_options) ? array_filter($tracking_options) : array();

  $page['#attached']['drupalSettings']['data']['google_analytics_vimeo'] = array(
    'progress25'     => $tracking_options['googleanalytics_vimeo_progress25'],
    'progress50'     => $tracking_options['googleanalytics_vimeo_progress50'],
    'progress75'     => $tracking_options['googleanalytics_vimeo_progress75'],
    'videoPlayed'    => $tracking_options['googleanalytics_vimeo_videoPlayed'],
    'videoPaused'    => $tracking_options['googleanalytics_vimeo_videoPaused'],
    'videoResumed'   => $tracking_options['googleanalytics_vimeo_videoResumed'],
    'videoSeeking'   => $tracking_options['googleanalytics_vimeo_videoSeeking'],
    'videoCompleted' => $tracking_options['googleanalytics_vimeo_videoCompleted'],
  );

  if ($google_analytics_vimeo_visibility_pages) {
    $page['#attached']['library'][] = 'google_analytics_vimeo/vimeo.ga.js';
    $page['#attached']['library'][] = 'google_analytics_vimeo/google_analytics_vimeo';
  }
}

/**
 * Implements hook_libraries_info().
 */
function google_analytics_vimeo_libraries_info() {
  $libraries['vimeo.ga.js'] = array(
    'name' => 'Google Analytics Vimeo Video Tracking',
    'vendor url' => 'https://github.com/sanderheilbron/vimeo.ga.js',
    'download url' => 'https://github.com/sanderheilbron/vimeo.ga.js/archive/master.zip',
    'version' => '0.6',
    'files' => array(
      'js' => array(
        'vimeo.ga.min.js',
      ),
    ),
  );
  return $libraries;
}
